name: Flutter Tests

on:
  push:
    branches:
      - 'feat/**'

  pull_request:
    branches: [ dev ]

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5' 
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: flutter pub get
      
      - name: Create dummy .env
        run: |
          echo "CLOUDINARY_CLOUD_NAME=mock" > .env
          echo "CLOUDINARY_UPLOAD_PRESET=mock" >> .env
          echo "SERVER_CLIENT_ID=mock" >> .env
      
      - name: Analyze code
        run: flutter analyze
      
      - name: Run tests
        run: flutter test --coverage

  auto-merge:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feat/')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create and Merge PR
        run: |
          # '${{ github.ref_name }}' automatically gets the current branch name (e.g., feat/auth)
          gh pr create --base dev --head ${{ github.ref_name }} --title "feat: ${{ github.ref_name }} verified ✅" --body "Automated PR created after all tests passed successfully."
          gh pr merge --auto --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}